generalInformation:
  serviceAdminEmail: jarro06@gmail.com
  gheUsername: jarro06
  billingAccount: bill acount
  billingTeamName: bill team
  gheToken: ""
  adpAccessToken: ""
projectInformation:
  projectName: Mój super nowy projekt
  projectShortName: "44119922343248555"
  buildType: maven
  testInstance: true
  preprodInstance: true
  uatInstance: false
cloudService:
  awsOrAzure: eks
  deploymentLocation: aws_ase2
  acpOrCRP: crp
  displayName: AZURE CLUSTER
  version: 2.4.5x
  productionCluster: false
  subscriptionId: ""
  enableStorageProvisioning: true
  ingressSubnetName: ""
  clusterSubnetName: ""
  adAdminGroupName: ""
  adViewerGroupName: ""
  adEditorGroupName: ""
  privateDnsZone: ""
  awsAccountId: ""
  instanceType: ""
  r53HostedZoneDomainName: ""
  sshWorkerKey: ""
  availabilityZones: ""
  az1HarmonizedSubnetId: ""
  az1WorkerSubnetId: ""
  az1PodSubnetId: ""
  az2HarmonizedSubnetId: ""
  az2WorkerSubnetId: ""
  az2PodSubnetId: ""
  az3HarmonizedSubnetId: ""
  az3WorkerSubnetId: ""
  az3PodSubnetId: ""
  workerSecurityGroupIds: ""
  ingressSecurityGroupIds: ""
  customDefinedAutomationAdminRole: ""
automationService:
  jenkinsOrGithubActions: jenkins
gheOrganisation:
  organisationName: jarro06
  isNew: false
testingTools:
  sonarQube: false
